### ISSUE TITLE
Firefox top menu issues

### ISSUE THREAD

**Issue by naasking** [owenversteeg/min#57] opened 2015-09-25 15:55 UTC
In Firefox 40, if you shrink the screen horizontally until you see the mobile menu at the top:
1. the "x" close button shows underneath the menu expansion button
2. the "x" close button isn't bottom-aligned with the rest of the menu, ie. it's lower than the menu
3. if you click "Min" in this menu, it briefly shows the menu but then the browser reloads the page and it goes away; I believe your intent is to merely show the menu (this happens in Chrome too, but Chrome doesn't have the other issues)

**Comment by owenversteeg** [comment] 2015-09-27 00:09
Hi! Thanks for reporting these issues. Much appreciated. 

I just confirmed that 1) and 2) are issues. I'll get to work on fixing them.

For 3) that is the intended behavior, and most hamburger menus on most sites work this way (including default Bootstrap for one.)

**Comment by naasking** [comment] 2016-10-31 17:32
Just thought I'd check this out again, and it's still an issue in the latest Firefox.

**Comment by owenversteeg** [comment] 2023-08-03 17:29
This has been resolved for years (after Firefox fixed their rendering) so closing :)

**Closed as completed by owenversteeg** 2023-08-03 17:29 UTC
